# Pair programming Intro a Pandas
El objetivo de la clase de hoy será crear unos cuántos DataFrames y Series a través de los siguientes
## Ejercicios:
1. ¿Qué diferencia hay entre una Serie y un DataFrame?
Una serie es unidimensional y un DataFrame es bidimensional

2. Momento de trabajar con Series. Contesta a las siguientes preguntas:
Crea dos listas:
- Una que se llame "valores" que tenga 7 números aleatorios.
- Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.
- A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie
y la variable indices sean los índices de la Serie.
- A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto
tenemos el método zip que nos permite iterar por dos listas a la vez. Más informción sobre este
método [aquí](https://www.programiz.com/python-programming/methods/built-in/zip)
- Crea una Serie con el diccionario creado en el punto anterior.
- ¿Qué forma tiene esta última Serie?
- ¿Qué tipo de datos tiene?
- ¿Qué tamaño tiene?
- ¿Cuáles son los índices de la Serie?
- ¿Y los values?
- Extrae el valor para el índice "lunes"
- Extrae el valor para el índice "lunes", "martes" y "miércoles".
- Extrae el valor para el índice "lunes" y "domingo".

In [14]:
import pandas as pd
import numpy as np

In [2]:
# Crea dos listas:
# Una que se llame "valores" que tenga 7 números aleatorios.
valores = [1,8,5,6,9,2,3]

# Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.
indices =  ["Lunes","Martes","Miercoles","Jueves","Viernes", "Sábado", "Domingo"]

# A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.
semana = pd.Series(valores, index=indices)
print(semana)
# A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más informción sobre este método aquí.

result = dict(zip(indices, valores))
result

Lunes        1
Martes       8
Miercoles    5
Jueves       6
Viernes      9
Sábado       2
Domingo      3
dtype: int64


{'Lunes': 1,
 'Martes': 8,
 'Miercoles': 5,
 'Jueves': 6,
 'Viernes': 9,
 'Sábado': 2,
 'Domingo': 3}

In [4]:
# Crea una Serie con el diccionario creado en el punto anterior.
# ¿Qué forma tiene esta última Serie?
semana2 = pd.Series(result)
semana2
# ¿Qué tipo de datos tiene?
    # int64
# ¿Qué tamaño tiene?
    #7
semana2.size

7

In [8]:
# ¿Cuáles son los índices de la Serie?
print(f"indices: {semana2.index}")
# ¿Y los values?
print(f"valores: {semana2.values}")

indices: Index(['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sábado',
       'Domingo'],
      dtype='object')
valores: [1 8 5 6 9 2 3]


In [9]:
# Extrae el valor para el índice "lunes"
print(f"valor lunes: {semana2['Lunes']}")

valor lunes: 1


In [12]:
# Extrae el valor para el índice "lunes", "martes" y "miércoles".
print(f"valor lunes, martes, miercoles:\n {semana2[['Lunes','Martes','Miercoles']]}")

valor lunes, martes, miercoles:
 Lunes        1
Martes       8
Miercoles    5
dtype: int64


In [13]:
# Extrae el valor para el índice "lunes" y "domingo".
print(f"valor lunes y domingo:\n {semana2[[0, -1]]}")

valor lunes y domingo:
 Lunes      1
Domingo    3
dtype: int64


3. Es el turno de los DataFrames
- Crea un array de dos dimensiones con 4 filas y 3 columnas.
- Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".
- Descarga el archivo "medallas" y carga el DataFrame.
- Usando el loc extrae todas las columnas de la fila de Tailandia.
- Usando el loc extrae todas las columnas de China e Irán.
- Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.
- Usando el iloc extrae la información de la India. 
- Devolved todas las columnas.
- Usando el iloc extrae todas las columnas de los paises que estén en posición impar. La
primera que nos tendría que salir es Japón y la última Corea del Norte.
- Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y
"Bronce".
- Contesta a las siguientes preguntas:
- ¿Qué país consiguió más de 200 medallas de oro?
- ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?
- ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?
- Crea una nueva columma que se llame "total" que sea el resultado de la suma de todas las
medallas obtenidas por cada país.


In [16]:
# Crea un array de dos dimensiones con 4 filas y 3 columnas.
array1 = np.empty((4,3))
print(f"array 4x3:\n {array1}")

array 4x3:
 [[4.68724220e-310 0.00000000e+000 1.03977794e-312]
 [9.54898106e-313 1.10343781e-312 1.01855798e-312]
 [1.23075756e-312 1.10343781e-312 1.03977794e-312]
 [9.76118064e-313 1.08221785e-312 1.90979621e-312]]


In [17]:
# Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".
nombre_columnas = ["España", "Francia", "Italia"]
df_medallas = pd.DataFrame(array1, columns=nombre_columnas)
print(f"df medallas:\n {df_medallas}")

df medallas:
           España        Francia         Italia
0  4.687242e-310   0.000000e+00  1.039778e-312
1  9.548981e-313  1.103438e-312  1.018558e-312
2  1.230758e-312  1.103438e-312  1.039778e-312
3  9.761181e-313  1.082218e-312  1.909796e-312


In [36]:
# Descarga el archivo "medallas" y carga el DataFrame.
df_medallas2 = pd.read_csv('medallas.csv', index_col=1)
print(f"df medallas2:\n {df_medallas2}")


df medallas2:
                  Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235


In [44]:
# Usando el loc extrae todas las columnas de la fila de Tailandia.
df_Thai = df_medallas2.loc['Tailandia',]
print(f"medallas Tailandia:\n {df_Thai}")

medallas Tailandia:
 Unnamed: 0      7
Oro           132
Plata         175
Bronce        278
Name: Tailandia, dtype: int64


In [43]:
# Usando el loc extrae todas las columnas de China e Irán.['Oro', 'Plata', 'Bronce']
df_Ch_I = df_medallas2.loc[['China', 'Irán'],]
print(f"medallas China e Irán:\n {df_Ch_I}")

medallas China e Irán:
        Unnamed: 0   Oro  Plata  Bronce
País                                  
China           1  1473    994     720
Irán            4   179    181     197


In [46]:
# Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.
df_Ch_I2 = df_medallas2.loc[['China', 'Irán'],['Oro', 'Plata', 'Bronce']]
print(f"medallas China e Irán:\n {df_Ch_I2}")

medallas China e Irán:
         Oro  Plata  Bronce
País                      
China  1473    994     720
Irán    179    181     197


In [49]:
# - Usando el iloc extrae la información de la India. Devolved todas las columnas.
print(df_medallas2.index)
df_Ind = df_medallas2.iloc[5,]
print(f"medallas India:\n {df_Ind}")

Index(['China', 'Japón', 'Corea del Sur', 'Irán', 'Kazajistán', 'India',
       'Tailandia', 'Indonesia', 'China Taipéi', 'Corea del Norte'],
      dtype='object', name='País')
medallas India:
 Unnamed: 0      6
Oro           154
Plata         202
Bronce        315
Name: India, dtype: int64


In [56]:
# Usando el iloc extrae todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.
df_impares = df_medallas2.iloc[1::2,]
print(f"impares:\n {df_impares}")

impares:
                  Unnamed: 0   Oro  Plata  Bronce
País                                            
Japón                     2  1032   1037     985
Irán                      4   179    181     197
India                     6   154    202     315
Indonesia                 8   112    131     240
Corea del Norte          10    91    120     235


In [57]:
# Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

df_impares2 = df_medallas2.iloc[1::2,1:4]
print(f"impares:\n {df_impares2}")

impares:
                   Oro  Plata  Bronce
País                                
Japón            1032   1037     985
Irán              179    181     197
India             154    202     315
Indonesia         112    131     240
Corea del Norte    91    120     235


In [59]:
# ¿Qué país consiguió más de 200 medallas de oro?
df_oro = df_medallas2.loc[df_medallas2['Oro'] > 200]
print(f"más 200 oros:\n {df_oro}")


más 200 oros:
                Unnamed: 0   Oro  Plata  Bronce
País                                          
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827


In [60]:
# ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?
df_oro_plata = df_medallas2.loc[(df_medallas2['Oro'] > 200) & (df_medallas2['Plata'] > 1000)]
print(f"más 200 oros y 1000 plata:\n {df_oro_plata}")

más 200 oros y 1000 plata:
        Unnamed: 0   Oro  Plata  Bronce
País                                  
Japón           2  1032   1037     985


In [61]:
# ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?  
df_oro_bronce = df_medallas2.loc[(df_medallas2['Oro'] > 200) | (df_medallas2['Bronce'] > 700)]
print(f"más 200 oros y 700 bronce:\n {df_oro_bronce}")

más 200 oros y 700 bronce:
                Unnamed: 0   Oro  Plata  Bronce
País                                          
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827


In [63]:
# Crea una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.
df_medallas2['Total'] = df_medallas2['Oro'] + df_medallas2['Plata'] + df_medallas2['Bronce']
print(f"medallas total: \n{df_medallas2}")

medallas total: 
                 Unnamed: 0   Oro  Plata  Bronce  Total
País                                                   
China                     1  1473    994     720   3187
Japón                     2  1032   1037     985   3054
Corea del Sur             3   745    663     827   2235
Irán                      4   179    181     197    557
Kazajistán                5   155    158     224    537
India                     6   154    202     315    671
Tailandia                 7   132    175     278    585
Indonesia                 8   112    131     240    483
China Taipéi              9    99    144     276    519
Corea del Norte          10    91    120     235    446
