In [2]:
# antes de empezar importamos la librería de NumPy para poder trabajar con todos sus métodos. 
import numpy as np

## Creación y Indexación:

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [2]:
ej_1=np.random.randint(10,100,50)
print(ej_1)
print('------------')
#No estamos seguras de si se refiere a empezar en el índice 5 o la quinta posición empezando desde el 0
print(ej_1[4::5])
print('------------')
print(ej_1[5::5])

[65 86 94 85 86 35 96 42 56 14 22 78 26 20 87 65 39 40 84 68 30 39 62 19
 32 62 36 74 16 52 75 27 74 53 39 62 27 29 77 79 60 86 47 61 77 14 99 77
 92 18]
------------
[86 14 87 68 32 52 39 79 77 18]
------------
[35 22 65 30 62 75 62 60 14]


2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares

In [3]:
ej_2=np.random.randint(1,21,30)
print(ej_2)
print('------------')
#No estamos seguras de si se refiere a empezar en el índice 1 o los impares empezando desde el 0
print(ej_2[::2])
print('------------')
print(ej_2[1::2])

[ 5 17  3  7 11  5 20  9  9 19 10 13 12  1  4 10 14  7 12 20 13 19  5 18
  3 20  5  5  4  3]
------------
[ 5  3 11 20  9 10 12  4 14 12 13  5  3  5  4]
------------
[17  7  5  9 19 13  1 10  7 20 19 18 20  5  3]


3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [4]:
ej_3=np.random.rand(4,6)*3
print(ej_3)
print('------------')
print(np.round(ej_3[-1:],2))


[[1.42789943 1.9287918  2.84757049 2.3499436  1.57453353 1.73363141]
 [2.22624438 1.78514555 2.6842512  0.56310741 1.90792523 1.99065792]
 [0.31089404 1.96358424 2.03875218 0.02050651 2.44474874 1.30846626]
 [1.29277462 2.20209694 1.5280483  0.34516307 2.67254111 1.59215749]]
------------
[[1.29 2.2  1.53 0.35 2.67 1.59]]


4.Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.

In [5]:
ej_4=np.random.rand(6,4)
print(ej_4)
print('------------')
print(np.round(ej_4[:,1],2))
#print(ej_4[:,1])

[[0.50382509 0.93717007 0.12064993 0.35057281]
 [0.13642962 0.30133511 0.65464393 0.16062915]
 [0.30460139 0.29424969 0.16112472 0.41681008]
 [0.54334922 0.11717939 0.35419709 0.31225108]
 [0.78893138 0.26499806 0.22978128 0.99832667]
 [0.9013206  0.00975691 0.61346036 0.04391613]]
------------
[0.94 0.3  0.29 0.12 0.26 0.01]


5. Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.

In [6]:
ej_5=np.random.randint(-50,51,30)
print(ej_5)
print('------------')

print(ej_5[ej_5<0])


[-22 -30 -39  21 -40 -44 -20 -50 -25 -36  14  13 -14  16  14 -48 -31  44
   1  30 -38 -41 -19 -43 -48  38 -23  41 -36  37]
------------
[-22 -30 -39 -40 -44 -20 -50 -25 -36 -14 -48 -31 -38 -41 -19 -43 -48 -23
 -36]


6. Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?

In [7]:
ej_6=np.random.rand(10)
print(np.round(ej_6,2))
print('------------')
print(np.where(ej_6>0.5))

[0.49 0.94 0.6  0.89 0.77 0.27 0.12 0.23 0.9  0.74]
------------
(array([1, 2, 3, 4, 8, 9]),)


7. Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.

In [8]:
ej_7=np.random.randint(1,101,40)
print(ej_7)
print('------------')
#No estamos seguras de si se refiere a empezar en el índice 5 o la quinta posición empezando desde el 0
div_3=ej_7%3
div_4=ej_7%4
print(ej_7[(div_3==0) & (div_4==0)])


[84 77 39 11  5 21 91 68  4 56 72 47 11 36 63 89  1 48 89 80  3 61 11 94
 58 84 45 88 52 34 92  1  4 33 84  1 46 14 94 52]
------------
[84 72 36 48 84 84]


BONUS+: Crea un array 1D de 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [7]:
ej_bon=np.random.randint(1,101,50)
print(ej_bon)
for x in range (0,50,3):
    ej_bon[x]=0
print(ej_bon)

[50 53 60 63  5 32 17 50 63 60  7 73 83  6 18 40 17 36 38 84 50 48 49 22
 15 53 10 64 20 36 46 80 62 32 86 35 88 50 12  1 67 72 73 89 12 93 98 95
 86  8]
[ 0 53 60  0  5 32  0 50 63  0  7 73  0  6 18  0 17 36  0 84 50  0 49 22
  0 53 10  0 20 36  0 80 62  0 86 35  0 50 12  0 67 72  0 89 12  0 98 95
  0  8]


Bonus: Crea un array 3D de forma (2, 3, 5) con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los valores múltiplos de 3 por 0.

In [11]:
ej_bon2=np.random.randint(1,101,(2,3,5))
print(ej_bon2)
print('-----------')
print(np.where(ej_bon2%3==0,0,ej_bon2))




[[[ 4 55  7 43 58]
  [13 29 82 93 83]
  [64 15 99 24 29]]

 [[90  8 53 12 60]
  [28 37 71 67 41]
  [85 48 25 63 23]]]
-----------
[[[ 4 55  7 43 58]
  [13 29 82  0 83]
  [64  0  0  0 29]]

 [[ 0  8 53  0  0]
  [28 37 71 67 41]
  [85  0 25  0 23]]]


[ 0 26 23  0 73 76  0 55 80  0 98 88  0 80  2  0 62 75  0  2 57  0 23 25
  0 33 86  0 81 77  0 21 51  0 19 18  0 83 76  0  2 11  0 28 77  0 66 44
  0 13]


## Reshape y Transpose:

- Ejercicios con reshape

1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [9]:
ej_1=np.random.randint(1,101,(2,3,4))
print(ej_1)
print('-------------')
print(np.reshape(ej_1,(4,6)))

[[[ 31  56 100  43]
  [ 33  22  67  91]
  [ 40   1  18  85]]

 [[ 38  19  81  52]
  [ 82  99  77  71]
  [100  71   8   2]]]
-------------
[[ 31  56 100  43  33  22]
 [ 67  91  40   1  18  85]
 [ 38  19  81  52  82  99]
 [ 77  71 100  71   8   2]]


2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [10]:
ej_2=np.random.randint(1,60,(3,4,5))
print(ej_2)
print('-------------')
print(np.reshape(ej_2,(5,12)))

[[[51 39 55  9 48]
  [51  3 21 35 59]
  [ 2  6 33 31 43]
  [48 15 37  4 37]]

 [[28 46 38 41 21]
  [ 4  2 37 14  5]
  [55  3 28  6 36]
  [50 15  6 46 27]]

 [[24 26 24  5 32]
  [20 45 34 57 23]
  [38 47 33 42  2]
  [20 17 12 48  8]]]
-------------
[[51 39 55  9 48 51  3 21 35 59  2  6]
 [33 31 43 48 15 37  4 37 28 46 38 41]
 [21  4  2 37 14  5 55  3 28  6 36 50]
 [15  6 46 27 24 26 24  5 32 20 45 34]
 [57 23 38 47 33 42  2 20 17 12 48  8]]


3. Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.

In [11]:
ej_3=np.random.rand(4,3,2)
print(ej_3)
print('-------------')
print(np.reshape(ej_3,(2,12)))

[[[0.11411146 0.77877174]
  [0.07303864 0.6375413 ]
  [0.3206512  0.92708521]]

 [[0.3995084  0.10594498]
  [0.42369769 0.7397382 ]
  [0.98250156 0.58355268]]

 [[0.59946564 0.91897461]
  [0.1076039  0.84900883]
  [0.21566031 0.66998044]]

 [[0.00564789 0.56549721]
  [0.48158029 0.87312655]
  [0.65320132 0.89237382]]]
-------------
[[0.11411146 0.77877174 0.07303864 0.6375413  0.3206512  0.92708521
  0.3995084  0.10594498 0.42369769 0.7397382  0.98250156 0.58355268]
 [0.59946564 0.91897461 0.1076039  0.84900883 0.21566031 0.66998044
  0.00564789 0.56549721 0.48158029 0.87312655 0.65320132 0.89237382]]


- Ejercicios con transpose

4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [12]:
print(ej_2)
print('-------------')
print(np.transpose(ej_2,(2,1,0)))

[[[51 39 55  9 48]
  [51  3 21 35 59]
  [ 2  6 33 31 43]
  [48 15 37  4 37]]

 [[28 46 38 41 21]
  [ 4  2 37 14  5]
  [55  3 28  6 36]
  [50 15  6 46 27]]

 [[24 26 24  5 32]
  [20 45 34 57 23]
  [38 47 33 42  2]
  [20 17 12 48  8]]]
-------------
[[[51 28 24]
  [51  4 20]
  [ 2 55 38]
  [48 50 20]]

 [[39 46 26]
  [ 3  2 45]
  [ 6  3 47]
  [15 15 17]]

 [[55 38 24]
  [21 37 34]
  [33 28 33]
  [37  6 12]]

 [[ 9 41  5]
  [35 14 57]
  [31  6 42]
  [ 4 46 48]]

 [[48 21 32]
  [59  5 23]
  [43 36  2]
  [37 27  8]]]


5. Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4).

In [13]:
print(ej_3)
print('-------------')
print(np.transpose(ej_3,(1,2,0)))

[[[0.11411146 0.77877174]
  [0.07303864 0.6375413 ]
  [0.3206512  0.92708521]]

 [[0.3995084  0.10594498]
  [0.42369769 0.7397382 ]
  [0.98250156 0.58355268]]

 [[0.59946564 0.91897461]
  [0.1076039  0.84900883]
  [0.21566031 0.66998044]]

 [[0.00564789 0.56549721]
  [0.48158029 0.87312655]
  [0.65320132 0.89237382]]]
-------------
[[[0.11411146 0.3995084  0.59946564 0.00564789]
  [0.77877174 0.10594498 0.91897461 0.56549721]]

 [[0.07303864 0.42369769 0.1076039  0.48158029]
  [0.6375413  0.7397382  0.84900883 0.87312655]]

 [[0.3206512  0.98250156 0.21566031 0.65320132]
  [0.92708521 0.58355268 0.66998044 0.89237382]]]


## Preguntas teóricas:

6. ¿Qué diferencia existe entre el reshape y el transpose?

El reshape, cambia la forma del array indicando la forma que quieres, mientras que el transpose la cambia utilizando las dimensiones previas cambiando el orden

7. ¿Y entre el transpose y el swapaxes?

El swapaxes sólo cambia 2 dimensiones entre ellas, los ejes.

## Funciones Aritméticas y Estadísticas:

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [22]:
ej_1=np.round(np.random.rand(2,3,5),1)
print(ej_1)

[[[0.8 1.  0.9 0.4 0.1]
  [1.  0.2 0.3 1.  0.8]
  [0.8 1.  0.7 0.6 0.6]]

 [[0.7 0.4 0.4 1.  0.8]
  [0.7 1.  0.5 0.5 0.8]
  [0.3 0.8 0.8 0.7 0.7]]]


2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
- Si el valor del array es igual que la media, se reemplaza por "A".
- Si el valor del array es mayor que la media, se reemplaza por "B".
- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".

In [36]:
ej_2=np.empty((2,3,5),dtype=str)
print(ej_2)
print('-----------')
print(ej_1)

[[['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]

 [['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]]
-----------
[[[0.8 1.  0.9 0.4 0.1]
  [1.  0.2 0.3 1.  0.8]
  [0.8 1.  0.7 0.6 0.6]]

 [[0.7 0.4 0.4 1.  0.8]
  [0.7 1.  0.5 0.5 0.8]
  [0.3 0.8 0.8 0.7 0.7]]]


In [37]:
#ej_2=np.array2string(ej_2)
media=np.round(np.mean(ej_1),1)
maximo=np.max(ej_1)
minimo=np.min(ej_1)
for i in range(0,ej_1.shape[0]):
    for j in range(0,ej_1.shape[1]):
        for k in range(0,ej_1.shape[2]):
            if ej_1[i,j,k]==(media):
                ej_2[i,j,k]='A'
            elif ej_1[i,j,k]==(maximo):
                ej_2[i,j,k]='D'
            elif ej_1[i,j,k]==(minimo):
                ej_2[i,j,k]='E'
            elif ej_1[i,j,k]>(media):
                ej_2[i,j,k]='B'
            elif ej_1[i,j,k]<(media):
                ej_2[i,j,k]='C'
            else:
                pass
print(ej_2)

[[['B' 'D' 'B' 'C' 'E']
  ['D' 'C' 'C' 'D' 'B']
  ['B' 'D' 'A' 'C' 'C']]

 [['A' 'C' 'C' 'D' 'B']
  ['A' 'D' 'C' 'C' 'B']
  ['C' 'B' 'B' 'A' 'A']]]


- Si el valor del array es igual que la media, se reemplaza por "A".

- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".

In [16]:
np.round(np.mean(ej_1),1)

0.5

In [17]:
#Si el valor del array es igual que la media, se reemplaza por "A".
ej_2=np.where(ej_2==(np.round(np.mean(ej_1),1)),'A',ej_2)
print(ej_2)

[[['0.6' '0.6' '1.0' '0.3' '0.3']
  ['0.8' '0.4' '0.3' '0.3' '0.8']
  ['0.0' '0.9' '0.9' '0.4' '0.1']]

 [['0.2' '0.0' 'A' '0.7' '0.6']
  ['0.9' '0.2' '0.0' '0.4' '0.8']
  ['0.3' '0.4' '0.3' '0.3' '0.8']]]


In [18]:
#- Si el valor del array es mayor que la media, se reemplaza por "B".
media=np.round(np.mean(ej_1),1)
ej_2=np.where((ej_2>media),'B',ej_2)
print(ej_2)

TypeError: '<' not supported between instances of 'numpy.ndarray' and 'numpy.ndarray'